theme: "hugo-PaperMod"
baseURL: https://data-gambit.netlify.app/
languageCode: en-us
title: Data Gambit
description: Miguel Salema

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

menu:
    main:
                - name: About 
                  url: about
                  weight: 10
                - name: Profile
                  url: archives
                  weight: 10
                - name: Archive
                  url: archives
                  weight: 10
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
                - name: Categories
                  url: categories/
                  weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: 
    author: Miguel Salema
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    # comments: false
    images: ["resources/_gen/images/pngegg.png"]

    profileMode:
        enabled: true
        Title: "Data Gambit"
        Subtitle: > 
                 Life is made of trade-offs  
                 
                 **Miguel Salema**
        Author: "**Miguel Salema**"
        description: "grewgwgw"
        imageUrl: "resources/_gen/images/pngegg.png"
        imageTitle: "<pngegg>" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags
              
        

    homeInfoParams:
        Title: "Data Gambit"
        Subtitle: "Life is made of trade-offs."
        Content: >
             **Miguel Salema**
   
   
    socialIcons:
        - name: github
          url: "https://github.com/Salema-DG?tab=repositories"
        - name: twitter
          url: "https://twitter.com/SalemaMiguel"


taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true