theme: "hugo-PaperMod"
baseURL: https://data-gambit.netlify.app/
languageCode: en-us
title: Data Gambit

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true


params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Data Gambit
    description: Here is a desription
    author: Miguel Salema
    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    # comments: false
    images: ["https://raw.githubusercontent.com/Salema-DG/Data_Gambit/main/resources/_gen/images/exp3.png"]
  
    profileMode:
        enabled: false
        Title: "Data Gambit"
        Subtitle: > 
                 Life is made of trade-offs  
                 
                 **Miguel Salema**
        Author: "**Miguel Salema**"
        
        #imageUrl: "resources/_gen/images/fig1.png"
        #images: "resources/_gen/images/fig1.png"
        imageUrl: "https://raw.githubusercontent.com/Salema-DG/Data_Gambit/main/resources/_gen/images/img5.png"
        imageTitle: "work" # optional
        imageWidth: 250 # custom size
        imageHeight: 250 # custom size
        buttons:
            - name: Archives
              url: archives
              
        

    homeInfoParams:
        Title: "Data Gambit"
        Content: >
             by **Miguel Salema** 
             <center>
             <img class="marginauto" src="https://raw.githubusercontent.com/Salema-DG/Data_Gambit/main/resources/_gen/images/img5.png" alt="centered image" width="200"/> 
             <center>
             
             Life is made of trade-offs
             
             
    socialIcons:
        - name: github
          url: "https://github.com/Salema-DG?tab=repositories"
        - name: twitter
          url: "https://twitter.com/SalemaMiguel"




    label:
        text: "Data Gambit"
        icon: "https://raw.githubusercontent.com/Salema-DG/Data_Gambit/main/resources/_gen/images/img5.png"
        iconHeight: 50















menu:
    main:
                - name: About 
                  url: archives
                  weight: 10
                - name: Profile
                  url: archives
                  weight: 10
                - name: Archive
                  url: archives
                  weight: 10
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
                - name: Categories
                  url: categories/
                  weight: 10
outputs:
    home:
        - HTML
        - RSS
        - JSON



cover:
    image: "https://raw.githubusercontent.com/Salema-DG/Data_Gambit/main/resources/_gen/images/exp3.pn" # image path/url
    caption: "<text>" # display caption under cover
    relative: false # when using page bundles set this to true
    hidden: false # only hide on current single page
    hiddenInSingle: false

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
              